
server:
  port: 8282

spring:
  data:
    mongodb:
      uri: mongodb+srv://linkedinclone:Superman123@linkedin-clone.nuwncve.mongodb.net
      database: linkedin
  datasource:
    url: jdbc:postgresql://ep-green-flower-49793442.us-east-2.aws.neon.tech/neondb
    username: akperrine
    password: 1WCmfL8aGUIX